### ISSUE TITLE
Multiple frontends / rules Evaluation order with ReplacePathRegex

### ISSUE THREAD

**Issue by abrugnon** [containous/traefik#3500]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to setup a docker based based Artifactory behing traefik as reverse proxy.
I need to implement several URL rewriting rules with ReplacePathRegex that can be evaluated in any order.

So far, i've ended up splitting the rules between frontends to keep one rule per frontend.

But it's impossible a achieve having the 2 Regex rules working at the same time, furthermore the result changes over docker-compose runs (without changing the compose file ...)

Find attached a docker-compose stripped down version to reproduce the behaviour.

### What did you expect to see?

- Frontend dns
  - curl localhost/fake         passing as  /fake
- Frontend repo
  - curl localhost/v2/token  rewritten as  /artifactory/api/docker/docker-login/v2/token
- Frontend auth
  - curl localhost/repo/test  rewritten as /artifactory/api/docker/repo/test

### What did you see instead?

Often only one regex Rule is OK and the other fails,  rarely everything fails

Is it the right way to achieve a multi ReplacePathRegex rule ?

I'm also afraid that there is a kind of randomness on the rule that succeeds. But the behavior is constant for each container startup.
It only vary when container restarts.

Here are the outputs of my tests :

curl localhost/repo/test    "path": "/artifactory/api/docker/repo/" OK
curl localhost/v2/token     "path": "/v2/token"  (KO : Not translated)
curl localhost/fake            "path": "/fake" OK

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.6.3
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-06-05_03:29:01PM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Docker compose v2 and traefik.toml

```toml

[accessLog]
  filePath = "/dev/stdout"
[traefikLog]
   filePath = "/dev/stdout"

[entryPoints]
  [entryPoints.http]
  address = ":80"
defaultEntryPoints = ["http"]

[docker]
domain = "docker.localhost"
watch = true
exposedbydefault = false

```

### Docker Compose sample

```yaml
version: '2.0'
services:

  traefik:
    image: traefik:1.6.3
    ports:
      - 80:80

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/abrugnon/bugreport/conf:/etc/traefik

  echosvc:
    image: mendhak/http-https-echo
    labels:
       traefik.backend: 'artifactory'
       traefik.enable: 'true'
       traefik.port: '80'

       traefik.dns.frontend.entryPoints: 'http'
       traefik.dns.frontend.backend: 'artifactory'
       traefik.dns.frontend.rule: "Host:localhost"
       
       traefik.repo.frontend.entryPoints: 'http'
       traefik.repo.frontend.backend: 'artifactory'
       traefik.repo.frontend.rule: "Host:localhost; ReplacePathRegex: ^/repo/(.*) /artifactory/api/docker/repo/$$2"
       
       traefik.auth.frontend.entryPoints: 'http'
       traefik.auth.frontend.backend: 'artifactory'
       traefik.auth.frontend.rule: "Host:localhost; ReplacePathRegex: ^/v2/token$$ /artifactory/api/docker/docker-login/v2/token"
```

**Comment by dtomcej** [comment]
Hello @abrugnon,

Took a look at your configuration, and the issue you are encountering is not a bug, but expected behaviour.

The issue you are encountering is due to overlapping rules.

You have one rule that matches `localhost/*` and another rule that matches `localhost/repo/*`, however anything that matches the second rule will also match the first. For this reason, depending on the order the rules get loaded in, they will be matched in different orders.

To make the rules behave the way you want to, you need to use the `traefik.<segment_name>.frontend.priority` label. By setting the priority for repo and auth to be higher, they will be matched first, regardless of in what order they are loaded. This should solve the issues you are encountering.

If you have any further questions, please stop by our slack channel: traefik.slack.com

Thanks!

**Comment by abrugnon** [comment]
Thanks @dtomcej for your answer.

BTW I've already tried the priority trick. With no luck

Here is the modified compose with priorities included ... still not working

```yaml
       traefik.dns.frontend.entryPoints: 'http'
       traefik.dns.frontend.backend: 'artifactory'
       traefik.dns.frontend.rule: "Host:localhost"
       traefik.dns.frontend.priority: "10"
       
       traefik.repo.frontend.entryPoints: 'http'
       traefik.repo.frontend.backend: 'artifactory'
       traefik.repo.frontend.rule: "Host:localhost; ReplacePathRegex: ^/repo/(.*) /artifactory/api/docker/repo/$$2"
       traefik.repo.frontend.priority: "500"
       
       traefik.auth.frontend.entryPoints: 'http'
       traefik.auth.frontend.backend: 'artifactory'
       traefik.auth.frontend.rule: "Host:localhost; ReplacePathRegex: ^/v2/token$$ /artifactory/api/docker/docker-login/v2/token"
       traefik.auth.frontend.priority: "400"
```

**Comment by ldez** [comment]
@abrugnon You have an issue with:
1. `traefik.backend: 'artifactory'`, you need to remove this label.
2. your replacement expression: you must use `$$1` instead of `$$2`

```yml
version: '2.0'
services:

  traefik:
    image: traefik:1.6.4
    command: --api --docker --docker.exposedbydefault=false --loglevel="DEBUG"
    ports:
      - 80:80
      - 8080:8080

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  echosvc:
    image: mendhak/http-https-echo
    labels:
       # traefik.backend: 'artifactory' # <-----
       traefik.enable: 'true'
       traefik.port: '80'

       traefik.dns.frontend.entryPoints: 'http'
       traefik.dns.frontend.backend: 'artifactory'
       traefik.dns.frontend.rule: "Host:whoami.docker.localhost"
       traefik.dns.frontend.priority: "10"

       traefik.repo.frontend.entryPoints: 'http'
       traefik.repo.frontend.backend: 'artifactory'
       traefik.repo.frontend.rule: "Host:whoami.docker.localhost; ReplacePathRegex: ^/repo/(.*) /artifactory/api/docker/repo/$$1"
       traefik.repo.frontend.priority: "500"

       traefik.auth.frontend.entryPoints: 'http'
       traefik.auth.frontend.backend: 'artifactory'
       traefik.auth.frontend.rule: "Host:whoami.docker.localhost; ReplacePathRegex: ^/v2/token$$ /artifactory/api/docker/docker-login/v2/token"
       traefik.auth.frontend.priority: "400"
```

**Comment by abrugnon** [comment]
thanks @ldez for pointing out regex mismatch (I  wrote a simplified version of the original compose file in order to tackle this point, but  IRL there are several traefik backends on this server).

But even with your modifications, the second rule (^/v2/token$) is not evaluated.

**Comment by ldez** [comment]
yes I have forget to say: `ReplacePathRegex` is a modifier, not a matcher.

<details>
<summary>docker-compose.yml</summary>

```yml
version: '2.0'
services:

  traefik:
    image: traefik:1.6.3
    command: --api --docker --docker.exposedbydefault=false --loglevel="DEBUG"
    ports:
      - 80:80
      - 8080:8080

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  echosvc:
    image: mendhak/http-https-echo
    labels:
       # traefik.backend: 'artifactory' # <-----
       traefik.enable: 'true'
       traefik.port: '80'
       traefik.frontend.entryPoints: 'http'

       # traefik.dns.backend: 'artifactory'
       traefik.dns.frontend.rule: "Host:whoami.docker.localhost"
       traefik.dns.frontend.priority: "10"

       # traefik.repo.backend: 'artifactory'
       traefik.repo.frontend.rule: "Host:whoami.docker.localhost; PathPrefix: /repo/{foo:.+};  ReplacePathRegex: ^/repo/(.*) /artifactory/api/docker/repo/$$1"
       traefik.repo.frontend.priority: "500"

       # traefik.auth.backend: 'artifactory'
       traefik.auth.frontend.rule: "Host:whoami.docker.localhost; PathPrefix: /v2/token; ReplacePathRegex: ^/v2/token$$ /artifactory/api/docker/docker-login/v2/token"
       traefik.auth.frontend.priority: "400"
```

</details>

<details>
<summary>curl</summary>


```console
$ curl whoami.docker.localhost/v2/token
{
  "path": "/artifactory/api/docker/docker-login/v2/token",
  "headers": {
    "host": "whoami.docker.localhost",
    "user-agent": "curl/7.47.0",
    "accept": "*/*",
    "x-forwarded-for": "172.24.0.1",
    "x-forwarded-host": "whoami.docker.localhost",
    "x-forwarded-port": "80",
    "x-forwarded-proto": "http",
    "x-forwarded-server": "d3ddd65cfe64",
    "x-real-ip": "172.24.0.1",
    "x-replaced-path": "/v2/token",
    "accept-encoding": "gzip"
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "whoami.docker.localhost",
  "ip": "::ffff:172.24.0.2",
  "ips": [],
  "protocol": "http",
  "query": {},
  "subdomains": [
    "whoami"
  ],
  "xhr": false,
  "os": {
    "hostname": "2a0ce972f84d"
  }
}
 
$ curl whoami.docker.localhost/repo/test
{
  "path": "/artifactory/api/docker/repo/test",
  "headers": {
    "host": "whoami.docker.localhost",
    "user-agent": "curl/7.47.0",
    "accept": "*/*",
    "x-forwarded-for": "172.24.0.1",
    "x-forwarded-host": "whoami.docker.localhost",
    "x-forwarded-port": "80",
    "x-forwarded-proto": "http",
    "x-forwarded-server": "d3ddd65cfe64",
    "x-real-ip": "172.24.0.1",
    "x-replaced-path": "/repo/test",
    "accept-encoding": "gzip"
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "whoami.docker.localhost",
  "ip": "::ffff:172.24.0.2",
  "ips": [],
  "protocol": "http",
  "query": {},
  "subdomains": [
    "whoami"
  ],
  "xhr": false,
  "os": {
    "hostname": "2a0ce972f84d"
  }
```

<details>

**Comment by abrugnon** [comment]
Thanks @ldez  for your help. 
The documentation is a bit fuzzy with ReplacePathRegex modifier and/or matcher  in paragraph Rules Order. 
I hope my mistakes will help other people.
Thanks again
