### ISSUE TITLE
WebSocket connections don't seem to upgrade correctly under HTTPS

### ISSUE THREAD

**Issue by Kazakuri** [containous/traefik#5533]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Tried to create a WebSocket connection through SocketIO over HTTPS.

### What did you expect to see?

A successful connection.

### What did you see instead?

An unsuccessful connection.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.1
Codename:     montdor
Go version:   go1.13.1
Built:        2019-09-26T16:18:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I've created a minimal example using [Flask-SocketIO](https://github.com/miguelgrinberg/Flask-SocketIO)'s example and forced it to use a WebSocket transport. The repo for it is [here](https://github.com/Kazakuri/traefik_websocket).

Accessing the app directly (`:5000`) or through Traefik's HTTP route (`:80`) works fine, but accessing it through Traefik's HTTPS route (`:443`) gets stuck where it appears to upgrade and then immediately drops the connection.

**Comment by rostikL** [comment]
You need to add `sslheader` middleware. Solution can be found here: https://community.containo.us/t/websockets-not-working-after-migrating-to-traefik-2-0/1912

**Comment by Kazakuri** [comment]
Hmm, it looks like `X-Forwarded-Proto` is already being set to `https` in the Traefik logs.

I added the middleware in anyways, but it doesn't appear to have changed anything.
I added these two labels to the service in `docker-compose.yml`:

```
- "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
- "traefik.http.routers.app-secure.middlewares=sslheader@docker"
```

**Comment by dduportal** [comment]
Hi @Kazakuri , did you solve the issue with the instructions given by @rostikL (thanks!) ?

**Comment by rostikL** [comment]
@Kazakuri That's strange. I have implemented the fix in our application and with the sslheaders middleware it works very well. 
I tried your example and can't get it to work there either. Maybe it has something to do with `cipherSuites` configuration?

**Comment by biblesyme** [comment]
I did a lot of research about this problem, I think it is more about Rancher.
Below is the research I did with one of my colleague. Hope it also helps you guys.

# Why will we get 302, 403, or even 404 instead of 101 when we delegate Secure WebSocket of Rancher 2.x deployed under HA strategy?

It's a fairly long story, I will keep it short as soon as possible.

If you are using Rancher single node, you shouldn't encounter these problems.
Well, if you are delegating Rancher HA installed under the guide of the official website. You may have these problems, to be more clearly specified, I will start from the very beginning. The whole transfer router will be like bellow when you delegate Rancher HA.

![Rancher HA Delegation (1)](https://user-images.githubusercontent.com/9334435/68847516-cafe8780-0709-11ea-912f-d5dc4dab9d42.png)


There are three major steps in this situation.

1. Proxy to External Loadbalancer of Rancher
2. Switch from https to http by Nginx Ingress Controller to finish the SSL Termination
3. Hit port 80 of Rancher Container

## To answer the first question of why we get 302
First, we need to better understand how Rancher determines if a request should be treated as `Https` or `Http`. Because we all know that 302 will be returned if Rancher thinks you are requesting as Http.
If you access 80 of Rancher directly, you will get a redirect to 443, which are handled by the function `httpRedirect` Below, these logics will only be applied when you hit Rancher on Port 80. I will explain more below.

Below are the source codes of Rancher to handle this logic
located on `pkg/dynamiclistener/server.go`

![35971a814fc5698f2079cf0f981c55bc](https://user-images.githubusercontent.com/9334435/68847542-d356c280-0709-11ea-9727-086b4c13df33.jpg)

From the [Line 505](https://github.com/rancher/rancher/blob/9930781c8f2be0228ab273752ad090c1f55a9d65/pkg/dynamiclistener/server.go#L505)) to [Line 508](https://github.com/rancher/rancher/blob/9930781c8f2be0228ab273752ad090c1f55a9d65/pkg/dynamiclistener/server.go#L508), we get to know that Rancher will detect the value of `X-Forwarded-Proto` to determine if your request should be redirected to a port of `**443`(According to the function starting from [Line 518](https://github.com/rancher/rancher/blob/9930781c8f2be0228ab273752ad090c1f55a9d65/pkg/dynamiclistener/server.go#L508)] )or not, besides personally I have no idea why they mangle port  like this, it’s kind of wired in this situation.  Because if your proxy server run on port `30002`, you will get a `302` response which redirect you to port `30443`, that's because the calculation in ([Line 529](https://github.com/rancher/rancher/blob/9930781c8f2be0228ab273752ad090c1f55a9d65/pkg/dynamiclistener/server.go#L529)). That's what I encountered in my case, in order to find out what's going on here, it cost me and my colleague a whole day.

Ok, now, we can start to explain why you will get 302 in your case. Definitely, it has something with the parameter `X-Forwarded-Proto`. If your proxy added an extra `wss` to this parameter or any other, it will fail at[ Line 505](https://github.com/rancher/rancher/blob/9930781c8f2be0228ab273752ad090c1f55a9d65/pkg/dynamiclistener/server.go#L505). Then, 302 returned.
Unfortuanately, a lot of wss proxy package will add `wss` to the `X-Forwarded-Proto` request header before redirect the request. Like what `http-node-proxy`([node-http-proxy/ws-incoming.js at 9bbe486c5efcc356fb4d189ef38eee275bbde345 · http-party/node-http-proxy · GitHub](https://github.com/http-party/node-http-proxy/blob/9bbe486c5efcc356fb4d189ef38eee275bbde345/lib/http-proxy/passes/ws-incoming.js#L58)) did. In your case, I believe traefik also add something to `X-Forwarded-Proto` when delegating `wss`.

Now, I think all the enigma about 302 is resolved. you can verify my explanation by sending `ws` to 80 of rancher, while with `X-Forwarded-Proto` to `Https`, you will find that it was connected successfully. I recommend you test `ws` with the tool `wscat`[GitHub - websockets/wscat: WebSocket cat](https://github.com/websockets/wscat) and test it like the command below
```
wscat -c "ws://10.10.11.34:32273/v3/subscribe” -n -H Authorization:”Bearer token-qt999:kcw55kqgkwsgsj55q2ps6gmpvw99c5vfp5mt4sh8kkwz5mnmk55x2s” -H x-forwarded-proto:”https”
```

![image](https://user-images.githubusercontent.com/9334435/68848683-ad322200-070b-11ea-8569-4033c652f233.png)

***Here my rancher’s 80 port was exposed as `32273`, and you should create a Bearer token to test it.***

you will find even though you hit the 80 of Rancher, you can still successfully connect to it as long as `x-forwarded-proto` is set to `https`, otherwise, it will return 302.

Next, I will explain other problems you may encounter when you delegate Rancher HA behind Proxy, if you are interested in, you can continue to read, just to avoid more people confusing here.

##  To answer the second question of why we get 403
We all know that 403 returned If your request is invalid. You may ask here why is that all of the `https` requests are proxied normally, while the `wss` returned 403. The short answer is that Rancher didn’t disable the Same Origin Policy for `wss`, while for `http` request they disabled it.  What’s more, Rancher also need the parameter `x-forwarded-host` match, I have no idea why they design like this so far. I will give my case why  I triggered the same-origin policy here. Hope it will help others to address the problem they may have.

In my case, my proxy is served on, for example, `localhost:3000`, and I want it proxy to Rancher at `www.test.com`. Then, what my proxy does is that set the request like `origin:”https://www.test.com”`; `host:www.test.com`; `x-forwarded-host:localhost`, and then send it to Rancher at  `www.test.com`. I did this because rancher/ui did the same thing. [ui/api.js at fa1b05dc25124aecd175b8f5fdbe18dcdc065fdc · rancher/ui · GitHub](https://github.com/rancher/ui/blob/fa1b05dc25124aecd175b8f5fdbe18dcdc065fdc/server/proxies/api.js#L48). Yes, you are right, even rancher’s developer, they face the same problem if they connect their front-end to HA instance. But I guess they won’t develop UI based on HA.

After I tried a lot of times using `wscat`, the results below tell me what happened in Rancher.

<img width="964" alt="Screen Shot 2019-11-14 at 17 39 18" src="https://user-images.githubusercontent.com/9334435/68847610-ea95b000-0709-11ea-8fc4-5dbcec620e73.png">

Maybe someone from Rancher can give a more specified explanation here.

##  To answer the second question of why we get 404

This is the easiest one to understand, because in step 2 above.  Under the HA strategy, your https request is terminated on Nginx Ingress Controller,  if your ‘host’ didn’t match the domain you set in Ingress rule, the Ingress controller have no idea where you wanna go. The screenshot below showed this case.

<img width="967" alt="Screen Shot 2019-11-14 at 17 59 20" src="https://user-images.githubusercontent.com/9334435/68847635-f1242780-0709-11ea-9c03-9f8930bb3c6a.png">

**Comment by Kazakuri** [comment]
I was playing with this a bit more this morning, and the browser shows the 101 Upgrade response fine, but somewhere within the internals of SocketIO there's some sort of internal request bouncing around that fails and closes the WebSocket connection.

From a quick look at it, it's returning a 400 BAD REQUEST because it checks the `HTTP_ORIGIN: https://app.docker.local` header and it doesn't match `http://app.docker.local`.

There was a commit to the EngineIO repo recently that added a check against `HTTP_X_FORWARDED_PROTO`, but there hasn't bee a release for that yet.
In either case, that internal request sends a `HTTP_X_FORWARDED_PROTO` header with the value `wss` (despite my attempts to modify it with Traefik middleware) which still doesn't match what it's looking for from the `HTTP_ORIGIN` header...

**Comment by bradjones1** [comment]
I'm not convinced this is really an error in Traefik; applications consuming websocket connections should probably know to test for `wss` or `https` for fullest compatibility.

FWIW, I placed an `nginx` proxy between Traefik 2 and Rancher 2; the config is below. The only point is to force `wss` back to `https` by setting `https` regardless of the upstream value (since we know the TLS termination has been done.) I also logged https://github.com/rancher/rancher/issues/25061 against Rancher to address this, there.

```
    map $http_upgrade $connection_upgrade {
        default $http_upgrade;
        '' close;
    }
    resolver kube-dns.kube-system.svc.cluster.local;
    server {
      listen 80 default_server;
      location / {
        set $rancher "rancher.cattle-system.svc.cluster.local";
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto "https";
        proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        proxy_set_header Upgrade $connection_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_pass http://$rancher;
      }
    }
```

**Comment by ruidesousacampos** [comment]
> 
> 
> I was playing with this a bit more this morning, and the browser shows the 101 Upgrade response fine, but somewhere within the internals of SocketIO there's some sort of internal request bouncing around that fails and closes the WebSocket connection.
> 
> From a quick look at it, it's returning a 400 BAD REQUEST because it checks the `HTTP_ORIGIN: https://app.docker.local` header and it doesn't match `http://app.docker.local`.
> 
> There was a commit to the EngineIO repo recently that added a check against `HTTP_X_FORWARDED_PROTO`, but there hasn't bee a release for that yet.
> ~In either case, that internal request sends a `HTTP_X_FORWARDED_PROTO` header with the value `wss` (despite my attempts to modify it with Traefik middleware) which still doesn't match what it's looking for from the `HTTP_ORIGIN` header...~
> 
> **Edit:** Manually updating the EngineIO package to that git commit and applying the Traefik middleware for customRequestHeaders appears to have fixed the issue.

Still facing this issue using Socket.io, can you provide the specific commit that fixed it for you.

**Comment by Kazakuri** [comment]
Sure, the commit that fixed it for me was `3c221a` in python-engineio [here](https://github.com/miguelgrinberg/python-engineio/commit/3c221aaec7173a046ca42f6aff9be0915cf92237).

It got released in v3.11.0

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

Thanks again for your interest in Traefik!

I'm glad to close the issue because I think that the question has been answered (Yes, I'm quite an advanced AI :smile:)

Join our [Community Forum](https://community.containo.us/) for more [support](https://community.containo.us/c/traefik).
